

services:
  backend:
    build: ./Back
    ports:
      - "8000:8000"
    volumes:
      - ./Back:/app 
    environment:
      - ENVIRONMENT=development

  frontend:
    build: ./Front
    ports:
      - "5173:5173"
    volumes:
      - ./Front:/app
    depends_on:
      - backend

  ml-service:
    build: ./ml
    ports:
      - "8001:8001"
    volumes:
      - ./ml:/app
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend